# Generated by Django 4.1.13 on 2024-11-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_asistencia_user_alter_datosdomicilio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio'),
        ),
        migrations.AlterField(
            model_name='datosdomicilio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio'),
        ),
        migrations.AlterField(
            model_name='datosfisicos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio'),
        ),
        migrations.AlterField(
            model_name='reservaclase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio'),
        ),
        migrations.AlterField(
            model_name='suscripción',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio'),
        ),
        migrations.AlterField(
            model_name='tarjetapago',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio'),
        ),
    ]
