# Generated by Django 4.1.13 on 2024-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_asistencia_user_alter_datosdomicilio_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripción',
            old_name='precio',
            new_name='precio_inscripcion',
        ),
        migrations.AddField(
            model_name='suscripción',
            name='precio_suscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
