# Generated by Django 4.1.13 on 2024-12-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_precio_suscripción_precio_inscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioclase',
            old_name='id_clase',
            new_name='clase_colectiva',
        ),
        migrations.RenameField(
            model_name='reservaclase',
            old_name='id_horario_clase',
            new_name='horario_clase',
        ),
    ]
