# Generated by Django 4.1.13 on 2024-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_id_clase_horarioclase_clase_colectiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_socios/'),
        ),
    ]
