# Generated by Django 4.1.13 on 2024-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_socio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripción',
            name='proximo_pago',
            field=models.DateField(default='2025-01-12'),
            preserve_default=False,
        ),
    ]
