# Generated by Django 4.1.13 on 2024-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_suscripción_proximo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripción',
            name='duracion',
            field=models.CharField(max_length=100),
        ),
    ]
