# Generated by Django 4.1.13 on 2024-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_suscripción_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
    ]
