# Generated by Django 4.1.13 on 2024-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_socio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripción',
            name='suscripcion_activa',
            field=models.BooleanField(default=True),
        ),
    ]
