# Generated by Django 4.1.13 on 2024-12-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_suscripción_suscripcion_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfisicos',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datosfisicos',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datosfisicos',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='datosfisicos',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
