# Generated by Django 4.1.13 on 2024-12-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_datosfisicos_altura_alter_datosfisicos_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfisicos',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
