# Generated by Django 4.1.13 on 2024-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_datosfisicos_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfisicos',
            name='altura',
            field=models.IntegerField(blank=True, default=170, null=True),
        ),
    ]
