# Generated by Django 4.1.13 on 2024-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_datosfisicos_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfisicos',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, default=22, max_digits=4, null=True),
        ),
    ]
