# Generated by Django 4.1.13 on 2024-12-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_datosfisicos_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfisicos',
            name='altura',
            field=models.IntegerField(blank=True, default=172, null=True),
        ),
    ]
