# Generated by Django 4.1.13 on 2024-12-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_datosfisicos_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfisicos',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosfisicos',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='datosfisicos',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
